service:
  main:
    controller: main
    ports:
      http:
        port: 7878
controllers:
  main:
    type: statefulset
    containers:
      main:
        image:
          repository: "ghcr.io/onedr0p/radarr"
          tag: "5.2.6.8376"
        env:
          TZ: Europe/Oslo
        securityContext:
          runAsUser: 0 #https://github.com/onedr0p/containers/blob/main/apps/ubuntu/Dockerfile#L41C15-L41C18
          runAsGroup: 0
          fsGroup: 0
        probes:
          liveness:
            enabled: true
            ## Set this to true if you wish to specify your own livenessProbe
            custom: true
            ## The spec field contains the values for the default livenessProbe.
            ## If you selected custom: true, this field holds the definition of the livenessProbe.
            spec:
              exec:
                command:
                  - /usr/bin/env
                  - bash
                  - -c
                  - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                    read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10